[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pymath"
version = "1.0.0"
description = "Basic math functions not part of the Python standard library"
requires-python = ">=3.9"
